### PR TITLE
fix(http): remove aurelia-http-client dependency, closes #101

### LINKED ISSUE #101: Aurelia-Http dependency issue
**I'm submitting a bug report**
```
ERROR in ./node_modules/aurelia-slickgrid/dist/native-modules/filters/selectFilter.js
Module not found: Error: Can't resolve 'aurelia-http-client' in '.\node_modules\aurelia-slickgrid\dist\native-modules\filters'
```

* **Library Version:**
2.3.0

**Please tell us about your environment:**
* **Operating System:**
Windows 10

* **Bundler used (WebPack/RequireJS/SystemJS)**
Webpack with aurelia cli

* **Browser:**
all

* **Language:**
TypeScript

**Current behavior:**
The library requires the use of aurelia-http-client

**Expected/desired behavior:**

* **What is the expected behavior?**
The library should not require this library and throw this error

* **What is the motivation / use case for changing the behavior?**
This may not give a good user experience because the grid should work "out of the box". Many user will probably use aurelia's library, but we should not force them to do so, especially since the aurelia CLI does not install the aurelia-http-client with `au new`. 

I found this when starting a new application trying to create a simple 3 column grid where my API call was mocked. This library is found in the select filter and the main custom element used with `instance of` and to define a type for the parameter.

EDIT: Actually I forgot the fetch-client and http-client are two different libraries. Some users may only use the fetch-client.

### PR DESCRIPTION
**Pull request by ghiscoding**
This PR removes the `aurelia-http-client` dependencies. I tested and fixed both Filters & Editors (the latter is in `aurelia-slickgrid.ts`). 

I had to move the `Promise` check as the first check since incorrectly was getting caught by the other checks, after doing so it was all good. I tested with `console.log` on all 3 (Filter & Editor) and switch from `aurelia-http-client`, to `aurelia-fetch-client` to `Promise`.

### CODE REVIEW

File: aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts [hunk 1]
```diff
@@ -659,19 +658,19 @@ export class AureliaSlickgridCustomElement {
...
+        if (Array.isArray(response)) {
+          this.updateEditorCollection(column, response); // from Promise
+        } else if (response instanceof Response && typeof response.json === 'function') {
           if (response.bodyUsed) {
             throw new Error('[Aurelia-SlickGrid] The response body passed to collectionAsync was ' +
               'already read. Either pass the dataset from the Response ' +
               'or clone the response first using response.clone()');
           }
-
+          // from aurelia-fetch-client
```
Comment (jmzagorski) [inline aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts]: might be confusing to have this comment here. A Promise may or may not come from aurelia-fetch-client

File: aurelia-slickgrid/src/aurelia-slickgrid/filters/selectFilter.ts [hunk 2]
```diff
@@ -1,414 +1,413 @@
...
+      // wait for the "collectionAsync", once resolved we will save it into the "collection"
+      const response: any | any[] = await collectionAsync;
 
-            if (!Array.isArray(awaitedCollection)) {
-                throw new Error('Something went wrong while trying to pull the collection from the "collectionAsync" call');
-            }
+      if (Array.isArray(response)) {
+        awaitedCollection = response; // from Promise
+      } else if (response instanceof Response && typeof response['json'] === 'function') {
+        awaitedCollection = await response['json'](); // from aurelia-fetch-client
```
Comment (jmzagorski) [inline aurelia-slickgrid/src/aurelia-slickgrid/filters/selectFilter.ts]: Same as other comment, Response does not need to come from aurelia-fetch-client

File: aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts (hunk 1 above)
Comment (ghiscoding) [reply aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts]: I've put the comments to know where each came from. It was a bit confusing to know the source of each. `aurelia-http-client` and `aurelia-fetch-client`, are not using the same and regular `Promise` are catch by the 1st `if`. Do you have a better way of identifying this?

Comment (jmzagorski) [reply aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts]: The `Response` interface is not specific to `aurelia-fetch-client`. For example, your consumer could be using the native `fetch` api and you would still get the `Response` interface. Not sure you need to identify which API the user is using. I think that is part of the beauty of getting the `Response` object back.

Comment (ghiscoding) [reply aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts]: @jmzagorski 
are you suggesting to remove the comment completely? I just find it a little less clear doing so, but if that removes confusion then sure

Comment (jmzagorski) [reply aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts]: you can keep it if it seems more clear, I have no problem with that. However, be aware that I can use the https://github.com/github/fetch library and it will return `Response` too

Comment (ghiscoding) [reply aurelia-slickgrid/src/aurelia-slickgrid/aurelia-slickgrid.ts]: I'll change it for `// from Fetch` then :)

**Comment by ghiscoding** [comment]
@jmzagorski 
Updated the comment and I hope the indentation is back to normal, it should 2 spaces. I will stop using the insiders version of VSCode, that seems to be the cause.

Are you ok to approve and merge?
