### PR TITLE
fix(sorters): return -1 or 1 for invalid dates

### LINKED ISSUE #68: DateFilters in filter-conditions leave invalid/null dates in filter
**I'm submitting a bug report**
Unless this is by design?

* **Framework Version:**
1.13.0

* **Browser:**
all

* **Language:**
TypeScript

**Current behavior:**
An example is in the dateIsoFilterCondition, which will always filter for invalid dates as coded [here](https://github.com/ghiscoding/aurelia-slickgrid/blob/master/aurelia-slickgrid/src/aurelia-slickgrid/filter-conditions/dateIsoFilterCondition.ts#L8). (if the date is invalid, the row will not be filtered). So when a user filters for a specific date they will always get a data item with a invalid value in the date

**Expected/desired behavior:**

* **What is the expected behavior?**
invalid dates are filtered out of the result set

* **What is the motivation / use case for changing the behavior?**
If there are a large number of `NULL` dates these will be included in the filter and the filter will seem broken to the user.

### PR DESCRIPTION
**Pull request by jmzagorski**
Returning zero every time value1 or value 2 is invalid will result in an incorrect sort because it would not sort one value higher than the other (e.g if value1 was 2018-05-24 and value2 was null, these would be sorted as equals). We want invalid dates to be grouped together in the sort and this accomplishes that.

We could add additional logic such that if both were invalid that we return 0, but this commit does the job just fine. Since the logic was the same for every sorter, with the exception of format and strict, I created a utility function that took all the parameters

closes #68
associates to PR #69

### CODE REVIEW

**Comment by ghiscoding** [comment]
Looks good, however I was thinking to revisit this and completely remove `moment` from the equation. Using `moment.js` with 2 steps (1st date validity, 2nd date compare) is terribly slow compare to regular javascript `Date`. I just didn't have the time to revisit it, but over 1000 items, you can visually see less than a second with `Date` versus 2-3 sec with `moment`. I just don't know what is the best algorithm to validate a date without `moment`

**Comment by ghiscoding** [comment]
@jmzagorski 
However there is a way to improve performance with `null` dates... you don't need `moment` to know it's invalid, just check for `null` in the same `if`

File: aurelia-slickgrid/src/aurelia-slickgrid/sorters/sorterUtilities.ts [hunk 1]
```diff
@@ -27,3 +28,19 @@ export function sortByFieldType(value1: any, value2: any, fieldType: FieldType,
 
   return sortResult;
 }
+
+export function compareDates(sortDirection, value1, value2, format, strict?: boolean) {
+  let diff = 0;
+
+  if (!moment(value1, format, strict).isValid()) {
```
Comment (ghiscoding) [inline aurelia-slickgrid/src/aurelia-slickgrid/sorters/sorterUtilities.ts]: add the `null` check in both `if` condition, this will improve a lot performance. Please try with 5000+ rows and you should see a drastic improvement with the `null` check

**Comment by ghiscoding** [comment]
Added a `null` and empty string check, tested the Start Date column with 5000 rows. I see a 10x improvement with the `null` check (when there are null dates that is)
- with `null` check it took 1.2 sec to sort
- without `null` check it took 10.2 sec to sort

**Comment by jmzagorski** [comment]
wow great testing! Thank you for finishing this up, i got busy yesterday with preparing a release for my application. Your way is smarter since the main reason for this PR was missing dates, Great work!
